### ISSUE TITLE
Support for LVM / mdadm

### ISSUE THREAD

**Issue by nilsmeyer** [nilsmeyer/ansible-debootstrap#1]
The role should support setting up mdadm and LVM as well.

**Comment by MaximilianSchieder** [comment]
I will try to setup these as well. Its needed for @zeug to setup a proxmox host.

**Comment by nilsmeyer** [comment]
You might be happier with ZFS, I think proxmox has good support for it, although Ubuntu doesn't really seem interested in it anymore - there is still no package for 0.7...

**Comment by MaximilianSchieder** [comment]
You are right. But mdadm would be cool anyway. Because proxmox is based on debian, it shouldn't rly matter if I use mdadm or zfs.
