### ISSUE TITLE
Allow for different _bootstrap_target sizes

### ISSUE THREAD

**Issue by pward123** [nilsmeyer/ansible-debootstrap#30]
I was trying to use this rule to bootstrap an xubuntu workstation and had to increase the size of the _bootstrap_target here.
https://github.com/nilsmeyer/ansible-debootstrap/blob/master/tasks/bootstrap.yml#L16

It would be nice if this was exposed as a variable.

Really nice rule btw. I was going to roll my own, but it would have taken me forever and not been as good as what you've put together. Thanks!

**Comment by nilsmeyer** [comment]
Thank you for your kind words. As a workaround you can disable using a temporary filesystem, this is mostly for systems with a lot of RAM but a slow disk. Setting `use_tmpfs: false` should do this.

**Comment by pward123** [comment]
that'll work. thanks for the quick reply
