### ISSUE TITLE
Add support for dropbear initramfs

### ISSUE THREAD

**Issue by nilsmeyer** [nilsmeyer/ansible-debootstrap#4]
For remote system it makes sense to use dropbear in initramfs, , since this may be required for first boot when there is no iKVM available.

* install dropbear package
* convert newly generated ssh keys to dropbear format
* rebuild initramfs

Stretch goal:
* Add some sort of remote unlock script

**Comment by MaximilianSchieder** [comment]
I will try to setup these.

**Comment by nilsmeyer** [comment]
After re-designing the role to be (more) compatible with using other roles this should be its own role.
