### ISSUE TITLE
lsblk -J not available in debian jessie

### ISSUE THREAD

**Issue by telepath** [nilsmeyer/ansible-debootstrap#5]
https://github.com/nilsmeyer/ansible-debootstrap/blob/ceb72932c8cc8c24acf9ea0f769a0e3e07ae0360/tasks/partitions.yml#L20

json output for lsblk is only available from util-linux package version 2.27 on, debian jessie uses 2.25.
Since jessie is supportet for installation, it would be good to support is as initial system also.

**Comment by nilsmeyer** [comment]
I never really tested in on jessie I must admit, thank you for bringing this to my attention. The problem is that parsing the lsblk output is otherwise very complicated. I would like to have that data available as facts in ansible instead, so that may be an approach to take.

**Comment by nilsmeyer** [comment]
I you have a patch for this I'd be happy to accept, but I think supporting older Debian versions is likely futile.
